### ISSUE TITLE
 'cn.xiaozhibang:evaluation-sdk:jar:1.0-SNAPSHOT'这个依赖找不到

### ISSUE THREAD

**Issue by liugang1117** [fangpeng0011/yunlan#2]
Unresolved dependency: 'cn.xiaozhibang:evaluation-sdk:jar:1.0-SNAPSHOT'

请问一下，启动jzo2o-customer项目，报 'cn.xiaozhibang:evaluation-sdk:jar:1.0-SNAPSHOT'这个依赖找不到，怎么办？

**Comment by fangpeng0011** [comment]
已通过邮件新式发送Maven包

**Comment by chicumt** [comment]
> 已通过邮件新式发送Maven包
能给我也发一份吗 373610583@qq.com

**Comment by xiaoYoaix** [comment]
能给我也发一份吗 [981672419@qq.com]

**Comment by fangpeng0011** [comment]
有需要的可以自取
链接：https://pan.baidu.com/s/1PNU2w3pKzrqChZYhn9X0uA?pwd=dujf 
提取码：dujf 
--来自百度网盘超级会员V6的分享

**Comment by HZ-12** [comment]
> 有需要的可以自取 链接：https://pan.baidu.com/s/1PNU2w3pKzrqChZYhn9X0uA?pwd=dujf 提取码：dujf --来自百度网盘超级会员V6的分享

感谢佬、

**Comment by HZ-12** [comment]
> Unresolved dependency: 'cn.xiaozhibang:evaluation-sdk:jar:1.0-SNAPSHOT'
> 
> 请问一下，启动jzo2o-customer项目，报 'cn.xiaozhibang:evaluation-sdk:jar:1.0-SNAPSHOT'这个依赖找不到，怎么办？

你好 请问一下问题解决了吗  为什么下载这个文件后 这个jar包是空的
